# Generated by Django 5.0.1 on 2024-06-11 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
                ('location', models.CharField(default='', max_length=100)),
                ('extension', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('CAR', 'CAR'), ('BUS', 'BUS'), ('MINIBUS', 'MINIBUS'), ('VAN', 'VAN'), ('TRUCK', 'TRUCK'), ('BIKE', 'BIKE')], default='CAR', max_length=50)),
                ('km_per_liter', models.FloatField(blank=True, default=0)),
                ('current_milage', models.IntegerField(blank=True, default=0)),
                ('license_plate', models.CharField(default='', max_length=20, unique=True)),
                ('fuel_level', models.FloatField(blank=True, default=0)),
                ('vehicle_status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('IN_USE', 'IN_USE'), ('RESERVED', 'RESERVED'), ('OUT_OF_SERVICE', 'OUT OF SERVICE')], default='AVAILABLE', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(max_length=200)),
                ('access_level', models.IntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refuel_request_date', models.DateField(default='')),
                ('refuel_date', models.DateField(default='')),
                ('fuel_type', models.CharField(choices=[('BENZINE', 'BENZINE'), ('NAFTA', 'NAFTA')], default='NAFTA', max_length=50)),
                ('km_during_refuel', models.IntegerField()),
                ('km_during_previous_refuel', models.IntegerField()),
                ('km_per_liter', models.FloatField()),
                ('current_fuel_level', models.FloatField()),
                ('remark', models.CharField(default='', max_length=500)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_request.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField(blank=True, default=None)),
                ('departure_time_est', models.TimeField(blank=True, default=None)),
                ('departure_time_act', models.TimeField(default='00:00:00')),
                ('departure_milage', models.IntegerField(default=0)),
                ('return_date_est', models.DateField(default='1970-01-01')),
                ('return_date_act', models.DateField(default='1970-01-01')),
                ('return_time_est', models.TimeField(default='00:00:00')),
                ('return_time_act', models.TimeField(default='00:00:00')),
                ('return_milage', models.IntegerField(default=0)),
                ('refuel_liters', models.FloatField(default=0.0, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatcher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_driver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dispatch_request.driver')),
                ('assigned_vehicle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dispatch_request.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='', max_length=500)),
                ('requested_vehicle_type', models.CharField(choices=[('CAR', 'CAR'), ('BUS', 'BUS'), ('MINIBUS', 'MINIBUS'), ('VAN', 'VAN'), ('TRUCK', 'TRUCK'), ('BIKE', 'BIKE')], default='CAR', max_length=50)),
                ('destination', models.CharField(default='', max_length=200)),
                ('destination_type', models.CharField(choices=[('ADDIS_ABABA', 'ADDIS ABABA'), ('AROUND_ADDIS_ABABA', 'AROUND ADDIS ABABA'), ('REGIONAL', 'REGIONAL')], default='ADDIS ABABA', max_length=50)),
                ('duration_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_time_from', models.TimeField(blank=True, default='')),
                ('duration_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_time_to', models.TimeField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requests', to='dispatch_request.dispatch')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_request.vehiclerequest')),
            ],
        ),
    ]
